"""Module containing the traffic routing execution event for the ECLYPSE framework."""

import random
from collections import defaultdict
from eclypse.workflow.event import EclypseEvent
from eclypse.workflow.trigger import CascadeTrigger
from network_application import NetworkAwareApplication
from network import Network
from constants import (
    DEFAULT_BANDWIDTH_MBPS,
    SEC_TO_MS
)

def build_probabilistic_queue(incoming_queues: dict[str, list], bandwidths: dict[str, float]) -> list:
    """It merges the input queues in a probabilistic manner based on bandwidth.

    Implement a probabilistic multiplexer: it extracts packets from the input
    queues by tossing a 'weighted coin' based on the bandwidth values.
    """
    merged_queue = []

    # Continue until there is at least one packet in any of the queues.
    while any(incoming_queues.values()):
        # Filter out sources that still have packages
        active_sources = [src for src, q in incoming_queues.items() if len(q) > 0]
        # Retrieve the associated weights (bandwidth)
        active_weights = [bandwidths[src] for src in active_sources]
        # Probabilistic extraction of the packet with P = Bandwidth / Sum(Bandwidths)
        chosen_source = random.choices(active_sources, weights=active_weights, k=1)[0]
        # Remove the packet from the original queue and insert it into the merged queue
        packet = incoming_queues[chosen_source].pop(0)
        merged_queue.append(packet)

    return merged_queue

class TrafficRoutingExecutionEvent(EclypseEvent):
    """Worker event that executes routing logic and updates application state.

    This event is called exactly once per step by the simulation engine. It is
    responsible for taking generated packets, resolving their source and
    destination placements, performing the heavy routing calculations, and
    moving the results to the completed packets basket.
    """
    def __init__(self, step_duration_s=0.001):
        """Initialize the traffic routing execution event.

        Args:
            step_duration_s (float): The duration of a single simulation step
                in seconds. Defaults to 0.001.
        """
        self.step_duration_s = step_duration_s
        super().__init__(
            name="traffic_routing_execution",
            event_type="application",
            triggers=[CascadeTrigger("step")]
        )


    def __call__(self, app: NetworkAwareApplication, placement, infra: Network, **kwargs):
        """Execute the routing logic for packets generated in the current step."""
        # Clear the step telemetry to prepare for new data collection during this step's execution
        infra.step_telemetry.clear()
        current_time_s = app.current_step * self.step_duration_s

        # Temporary buffer to hold packets for the next step after forwarding
        # We need this because we want to process all routers' buffers in parallel
        # before moving packets to the next router.
        next_step_buffers = defaultdict(list)

        # Inject the packets generated by the application into the source routers' buffers
        for packet in app.generated_packets:
            try:
                src_node = placement.service_placement(service_id=packet.src)
                dst_node = placement.service_placement(service_id=packet.dst)
            except KeyError:
                continue

            packet.src = src_node
            packet.dst = dst_node
            packet.current_node = src_node

            # Put the packet in the source router's buffer to be processed in the next phase
            infra.router_buffers[src_node].append(packet)

        app.generated_packets.clear()

        # Scan all router buffers to identify contention points and group packets accordingly
        active_routers = list(infra.router_buffers.keys())

        for router in active_routers:
            buffer = infra.router_buffers[router]
            if not buffer:
                continue

            incoming_queues = defaultdict(list)
            for pkt in buffer:
                incoming_queues[pkt.previous_node].append(pkt)

            bws = {}
            for prev_node in incoming_queues:
                if prev_node == "APP":
                    bws[prev_node] = DEFAULT_BANDWIDTH_MBPS * 10
                else:
                    edge_data = infra.get_edge_data(prev_node, router, default={})
                    bws[prev_node] = edge_data.get('bandwidth_mbps', DEFAULT_BANDWIDTH_MBPS)

            shuffled_packets = build_probabilistic_queue(incoming_queues, bws)
            # Log the order of packets after shuffling for debugging purposes
            if len(shuffled_packets) > 1:
                order_log = ", ".join([f"{p.id} ({p.previous_node})" for p in shuffled_packets])
                infra.logger.info(f"{router} order: [{order_log}]")

            # Forward each packet one hop at a time, updating its state and moving it to the next buffer or completed list
            for pkt in shuffled_packets:
                # Ask the infrastructure to forward the packet one hop towards its destination, and get the next node
                next_node = infra.forward_one_hop(pkt, current_time_s)

                if next_node is not None:
                    # If the next hop is the destination, the packet is delivered
                    if next_node == pkt.dst:
                        app.completed_packets.append(pkt)
                    else:
                        # Otherwise, put it in the next hop buffer
                        next_step_buffers[next_node].append(pkt)

            infra.router_buffers[router].clear()

        # Move the landed packets to the new routers for the next round
        for router, pkts in next_step_buffers.items():
            infra.router_buffers[router].extend(pkts)
