from eclypse.graph import Application


class NetworkAwareApplication(Application):
    """
    Extension of the standard ECLYPSE application class that incorporates
    network traffic characteristics.

    Unlike the base Application class which defines primarily through
    abstract requirements (like latency or bandwidth constraints), this class
    allows the definition of volumetric traffic flows (packet size and rate).
    This is essential for packet-level simulations where queueing delays and
    congestion need to be modeled.
    """

    def add_flow(self, source: str, target: str, packet_size_bytes: int,
                 packets_per_tick: int, **kwargs):
        """
        Adds a directed logical link (flow) between two services with specific
        parameters.
        This method stores the traffic generation logic into the graph edge,
        allowing the simulation to generate discrete packets during execution.

        Args:
            source (str): The ID of the source service (the sender).
            target (str): The ID of the target service (the receiver).
            packet_size_bytes (int): The size of a single packet in bytes.
                Must be > 0.
            packets_per_tick (int): The number of packets generated by the
                source for this flow during. Must be >= 0.
            **kwargs: Additional edge attributes supported by ECLYPSE (e.g.,
                'max_latency', 'required_bandwidth').
        Raises:
            ValueError: If `packet_size_bytes` is <= 0 or `packets_per_tick` is < 0.
        """
        if packet_size_bytes <= 0:
            raise ValueError("The dimensions of the packet must be > 0. Found: {packet_size_bytes}")
        if packets_per_tick < 0:
            raise ValueError("The rate of the packets must be >= 0. Found: {packets_per_tick}")

        # Calculate the bandwidth requested (Throughput)
        throughput_per_tick = packet_size_bytes * packets_per_tick

        # Add the edge using the add_edge method
        self.add_edge(
            source,
            target,
            packet_size_bytes=packet_size_bytes,
            packets_per_tick=packets_per_tick,
            required_throughput_per_tick=throughput_per_tick,
            **kwargs
        )

        print(f"Add edge flow {source}->{target}: {packets_per_tick} pkt/tick with packet size {packet_size_bytes} Bytes")